// ─── Demo data for the AuditX prototype ─────────────────────────────────────
// All numbers are realistic but fictitious. Real FIFO math is in lib/tax.ts.

export type TxAction = "BUY" | "SELL" | "DIV";
export type TxStatus = "posted" | "needs_review";

export interface Transaction {
  id: string;
  ticker: string;
  action: TxAction;
  quantity: number;
  price: number;
  fees: number;
  wht: number;
  trade_date: string;
  ref_id: string;
  confidence_score: number;
  status: TxStatus;
  broker: string;
  exchange: "PSX" | "NSE";
}

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: "t001",
    ticker: "OGDC",
    action: "BUY",
    quantity: 500,
    price: 98.5,
    fees: 1240,
    wht: 0,
    trade_date: "2025-07-15",
    ref_id: "PSX-7192-A",
    confidence_score: 0.97,
    status: "posted",
    broker: "Meridian Capital",
    exchange: "PSX",
  },
  {
    id: "t002",
    ticker: "HBL",
    action: "BUY",
    quantity: 200,
    price: 154.0,
    fees: 780,
    wht: 0,
    trade_date: "2025-07-18",
    ref_id: "PSX-7201-B",
    confidence_score: 0.91,
    status: "posted",
    broker: "Meridian Capital",
    exchange: "PSX",
  },
  {
    id: "t003",
    ticker: "TCS",
    action: "BUY",
    quantity: 50,
    price: 3840.0,
    fees: 4800,
    wht: 0,
    trade_date: "2025-07-20",
    ref_id: "NSE-44120",
    confidence_score: 0.95,
    status: "posted",
    broker: "Nifty Desk",
    exchange: "NSE",
  },
  {
    id: "t004",
    ticker: "OGDC",
    action: "SELL",
    quantity: 300,
    price: 114.75,
    fees: 860,
    wht: 0,
    trade_date: "2025-08-02",
    ref_id: "PSX-7388-C",
    confidence_score: 0.93,
    status: "posted",
    broker: "Meridian Capital",
    exchange: "PSX",
  },
  {
    id: "t005",
    ticker: "MCB",
    action: "DIV",
    quantity: 1000,
    price: 4.5,
    fees: 0,
    wht: 450,
    trade_date: "2025-08-05",
    ref_id: "PSX-DIV-4921",
    confidence_score: 0.88,
    status: "posted",
    broker: "Meridian Capital",
    exchange: "PSX",
  },
  {
    id: "t006",
    ticker: "INFY",
    action: "BUY",
    quantity: 100,
    price: 1540.0,
    fees: 3850,
    wht: 0,
    trade_date: "2025-08-08",
    ref_id: "NSE-44512",
    confidence_score: 0.82,
    status: "posted",
    broker: "Nifty Desk",
    exchange: "NSE",
  },
  {
    id: "t007",
    ticker: "PPL",
    action: "BUY",
    quantity: 800,
    price: 79.25,
    fees: 1596,
    wht: 0,
    trade_date: "2025-08-10",
    ref_id: "PSX-7401-D",
    confidence_score: 0.96,
    status: "posted",
    broker: "SouthPort Securities",
    exchange: "PSX",
  },
  {
    id: "t008",
    ticker: "TCS",
    action: "SELL",
    quantity: 30,
    price: 4120.0,
    fees: 3080,
    wht: 0,
    trade_date: "2025-08-15",
    ref_id: "NSE-44891",
    confidence_score: 0.79,
    status: "needs_review",
    broker: "Nifty Desk",
    exchange: "NSE",
  },
  {
    id: "t009",
    ticker: "UBL",
    action: "BUY",
    quantity: 400,
    price: 188.0,
    fees: 1880,
    wht: 0,
    trade_date: "2025-08-18",
    ref_id: "PSX-7455-E",
    confidence_score: 0.94,
    status: "posted",
    broker: "SouthPort Securities",
    exchange: "PSX",
  },
  {
    id: "t010",
    ticker: "ENGRO",
    action: "SELL",
    quantity: 150,
    price: 264.5,
    fees: 990,
    wht: 0,
    trade_date: "2025-08-20",
    ref_id: "PSX-7472-F",
    confidence_score: 0.71,
    status: "needs_review",
    broker: "Meridian Capital",
    exchange: "PSX",
  },
  {
    id: "t011",
    ticker: "LUCK",
    action: "BUY",
    quantity: 100,
    price: 420.0,
    fees: 1050,
    wht: 0,
    trade_date: "2025-08-22",
    ref_id: "PSX-7501-G",
    confidence_score: 0.98,
    status: "posted",
    broker: "Meridian Capital",
    exchange: "PSX",
  },
  {
    id: "t012",
    ticker: "INFY",
    action: "DIV",
    quantity: 100,
    price: 18.0,
    fees: 0,
    wht: 270,
    trade_date: "2025-08-25",
    ref_id: "NSE-DIV-9901",
    confidence_score: 0.89,
    status: "posted",
    broker: "Nifty Desk",
    exchange: "NSE",
  },
];

export const DEMO_RECONCILIATION_FLAGS = [
  {
    id: "f001",
    flag_type: "Fee Surcharge",
    severity: "warn" as const,
    ticker: "OGDC",
    ref_id: "PSX-7388-C",
    expected: 688,
    actual: 860,
    description: "Broker fee exceeds standard SECP tariff by PKR 172",
    suggested_resolution: "Request broker fee memo or reclassify as premium service charge",
  },
  {
    id: "f002",
    flag_type: "WHT Mismatch",
    severity: "bad" as const,
    ticker: "MCB",
    ref_id: "PSX-DIV-4921",
    expected: 562.5,
    actual: 450,
    description: "WHT withheld at 10% (Filer) but account is registered as Non-Filer (12.5%)",
    suggested_resolution: "Contact MCB investor relations to recalculate correct WHT deduction",
  },
  {
    id: "f003",
    flag_type: "Low Confidence",
    severity: "warn" as const,
    ticker: "ENGRO",
    ref_id: "PSX-7472-F",
    expected: 0.85,
    actual: 0.71,
    description: "Extraction confidence below 0.75 threshold — manual review required",
    suggested_resolution: "Upload clearer document scan or enter fields manually",
  },
];

export const DEMO_AUDIT_LOG = [
  {
    id: "al001",
    timestamp: "2025-08-25T14:32:11Z",
    actor: "AuditX Agent",
    action: "parse_document",
    entity_type: "document",
    entity_id: "doc-012",
    prev_hash: "0x33c09e17b4a1",
    hash: "0x9f2ac41db8e2",
  },
  {
    id: "al002",
    timestamp: "2025-08-25T14:32:15Z",
    actor: "demo@auditx.io",
    action: "post_to_ledger",
    entity_type: "transaction",
    entity_id: "t012",
    prev_hash: "0x9f2ac41db8e2",
    hash: "0x71be08aa3f10",
  },
  {
    id: "al003",
    timestamp: "2025-08-22T09:11:04Z",
    actor: "AuditX Agent",
    action: "flag_discrepancy",
    entity_type: "reconciliation_flag",
    entity_id: "f002",
    prev_hash: "0xa1c903de7721",
    hash: "0x33c09e17b4a1",
  },
  {
    id: "al004",
    timestamp: "2025-08-20T18:45:22Z",
    actor: "demo@auditx.io",
    action: "compute_tax",
    entity_type: "tax_computation",
    entity_id: "tc001",
    prev_hash: "0x84ef12ab9c4d",
    hash: "0xa1c903de7721",
  },
  {
    id: "al005",
    timestamp: "2025-08-18T11:30:00Z",
    actor: "demo@auditx.io",
    action: "post_to_ledger",
    entity_type: "transaction",
    entity_id: "t009",
    prev_hash: "0x6b2d889fa012",
    hash: "0x84ef12ab9c4d",
  },
];
