/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppAuditTrailRouteImport } from './routes/app.audit-trail'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppInvestigationsRouteImport } from './routes/app.investigations'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppParserRouteImport } from './routes/app.parser'
import { Route as AppReconciliationRouteImport } from './routes/app.reconciliation'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTaxRouteImport } from './routes/app.tax'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppParserIndexRouteImport } from './routes/app.parser.index'
import { Route as AppParserThreadIdRouteImport } from './routes/app.parser.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditTrailRoute = AppAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsRoute = AppInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppParserRoute = AppParserRouteImport.update({
  id: '/parser',
  path: '/parser',
  getParentRoute: () => AppRoute,
} as any)
const AppReconciliationRoute = AppReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxRoute = AppTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppParserIndexRoute = AppParserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppParserRoute,
} as any)
const AppParserThreadIdRoute = AppParserThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppParserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/news': typeof NewsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agent': typeof AppAgentRoute
  '/app/audit-trail': typeof AppAuditTrailRoute
  '/app/billing': typeof AppBillingRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/parser': typeof AppParserRouteWithChildren
  '/app/reconciliation': typeof AppReconciliationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tax': typeof AppTaxRoute
<<<<<<< Updated upstream
  '/app/': typeof AppIndexRoute
=======
  '/app/timeline': typeof AppTimelineRoute
>>>>>>> Stashed changes
  '/app/parser/$threadId': typeof AppParserThreadIdRoute
  '/app/parser/': typeof AppParserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/news': typeof NewsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agent': typeof AppAgentRoute
  '/app/audit-trail': typeof AppAuditTrailRoute
  '/app/billing': typeof AppBillingRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reconciliation': typeof AppReconciliationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tax': typeof AppTaxRoute
<<<<<<< Updated upstream
  '/app': typeof AppIndexRoute
=======
  '/app/timeline': typeof AppTimelineRoute
>>>>>>> Stashed changes
  '/app/parser/$threadId': typeof AppParserThreadIdRoute
  '/app/parser': typeof AppParserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/news': typeof NewsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agent': typeof AppAgentRoute
  '/app/audit-trail': typeof AppAuditTrailRoute
  '/app/billing': typeof AppBillingRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/parser': typeof AppParserRouteWithChildren
  '/app/reconciliation': typeof AppReconciliationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tax': typeof AppTaxRoute
<<<<<<< Updated upstream
  '/app/': typeof AppIndexRoute
=======
  '/app/timeline': typeof AppTimelineRoute
>>>>>>> Stashed changes
  '/app/parser/$threadId': typeof AppParserThreadIdRoute
  '/app/parser/': typeof AppParserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/news'
    | '/pricing'
    | '/security'
    | '/signin'
    | '/signup'
    | '/api/chat'
    | '/app/agent'
    | '/app/audit-trail'
    | '/app/billing'
    | '/app/insights'
    | '/app/investigations'
    | '/app/ledger'
    | '/app/overview'
    | '/app/parser'
    | '/app/reconciliation'
    | '/app/reports'
    | '/app/settings'
    | '/app/tax'
<<<<<<< Updated upstream
    | '/app/'
=======
    | '/app/timeline'
>>>>>>> Stashed changes
    | '/app/parser/$threadId'
    | '/app/parser/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/news'
    | '/pricing'
    | '/security'
    | '/signin'
    | '/signup'
    | '/api/chat'
    | '/app/agent'
    | '/app/audit-trail'
    | '/app/billing'
    | '/app/insights'
    | '/app/investigations'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reconciliation'
    | '/app/reports'
    | '/app/settings'
    | '/app/tax'
<<<<<<< Updated upstream
    | '/app'
=======
    | '/app/timeline'
>>>>>>> Stashed changes
    | '/app/parser/$threadId'
    | '/app/parser'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/news'
    | '/pricing'
    | '/security'
    | '/signin'
    | '/signup'
    | '/api/chat'
    | '/app/agent'
    | '/app/audit-trail'
    | '/app/billing'
    | '/app/insights'
    | '/app/investigations'
    | '/app/ledger'
    | '/app/overview'
    | '/app/parser'
    | '/app/reconciliation'
    | '/app/reports'
    | '/app/settings'
    | '/app/tax'
<<<<<<< Updated upstream
    | '/app/'
=======
    | '/app/timeline'
>>>>>>> Stashed changes
    | '/app/parser/$threadId'
    | '/app/parser/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NewsRoute: typeof NewsRoute
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-trail': {
      id: '/app/audit-trail'
      path: '/audit-trail'
      fullPath: '/app/audit-trail'
      preLoaderRoute: typeof AppAuditTrailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigations': {
      id: '/app/investigations'
      path: '/investigations'
      fullPath: '/app/investigations'
      preLoaderRoute: typeof AppInvestigationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parser': {
      id: '/app/parser'
      path: '/parser'
      fullPath: '/app/parser'
      preLoaderRoute: typeof AppParserRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reconciliation': {
      id: '/app/reconciliation'
      path: '/reconciliation'
      fullPath: '/app/reconciliation'
      preLoaderRoute: typeof AppReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tax': {
      id: '/app/tax'
      path: '/tax'
      fullPath: '/app/tax'
      preLoaderRoute: typeof AppTaxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parser/': {
      id: '/app/parser/'
      path: '/'
      fullPath: '/app/parser/'
      preLoaderRoute: typeof AppParserIndexRouteImport
      parentRoute: typeof AppParserRoute
    }
    '/app/parser/$threadId': {
      id: '/app/parser/$threadId'
      path: '/$threadId'
      fullPath: '/app/parser/$threadId'
      preLoaderRoute: typeof AppParserThreadIdRouteImport
      parentRoute: typeof AppParserRoute
    }
  }
}

interface AppParserRouteChildren {
  AppParserThreadIdRoute: typeof AppParserThreadIdRoute
  AppParserIndexRoute: typeof AppParserIndexRoute
}

const AppParserRouteChildren: AppParserRouteChildren = {
  AppParserThreadIdRoute: AppParserThreadIdRoute,
  AppParserIndexRoute: AppParserIndexRoute,
}

const AppParserRouteWithChildren = AppParserRoute._addFileChildren(
  AppParserRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppAuditTrailRoute: typeof AppAuditTrailRoute
  AppBillingRoute: typeof AppBillingRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInvestigationsRoute: typeof AppInvestigationsRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppParserRoute: typeof AppParserRouteWithChildren
  AppReconciliationRoute: typeof AppReconciliationRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTaxRoute: typeof AppTaxRoute
<<<<<<< Updated upstream
  AppIndexRoute: typeof AppIndexRoute
=======
  AppTimelineRoute: typeof AppTimelineRoute
>>>>>>> Stashed changes
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppAuditTrailRoute: AppAuditTrailRoute,
  AppBillingRoute: AppBillingRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInvestigationsRoute: AppInvestigationsRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppParserRoute: AppParserRouteWithChildren,
  AppReconciliationRoute: AppReconciliationRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTaxRoute: AppTaxRoute,
<<<<<<< Updated upstream
  AppIndexRoute: AppIndexRoute,
=======
  AppTimelineRoute: AppTimelineRoute,
>>>>>>> Stashed changes
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  NewsRoute: NewsRoute,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
